# **Numpy Introduction**

In [29]:
!pip install numpy

In [2]:
# now we import the numby library 
import numpy as np

# **What is an array ?**


An array is a data structure that stores a collection of elements, each identified by an index. The elements in an array are usually of the same type, and the array has a fixed size, determined when the array is created. In PowerShell, arrays are created by placing the elements inside parentheses and separated by commas. The elements can be of any type, including other arrays, creating a multi-dimensional array. Arrays can be manipulated using various methods and properties, such as .Length, .Where(), and .ForEach().

In [3]:
a=np.arange(10)         # its is one dimensional array
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a.shape

(10,)

In [5]:
a_1=a[np.newaxis, :]                        # this is a two dimensional array
a_1

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [6]:
a_1.shape

(1, 10)

In [7]:
a_2=a[:, np.newaxis]                        # this is a two dimensional array
a_2

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [8]:
a_3=a_2[np.newaxis, :]                      # this is a three dimensional array
a_3

a_3.shape

(1, 10, 1)

## **Assingnment**

## **Why do we have 1D,2D and 3D arrays and where we need them in data sicence ?**

### **1D Arrays**
1D Arrays are used when we need to store a single row or column of data. They are useful when we need to perform operations on a single row or column of data. For example,we can use 1D arrays to store the scores of a student in a subject. We can use the array to perform operations like finding the maximum score, minimum score, average score, etc.

### **2D Arrays (Matrices)**

2D Arrays are used when we need to store data in a table format.They are useful when we need to perform operations on multiple rows and columns of data. For example,we can use 2D arrays to store the scores of students in a subject. We can use the array to perform operations like finding the maximum score, minimum score, average score, etc.

### **3D Arrays (Cubes)**

3D Arrays are used when we need to store data in a 3D format.They are useful when we need to perform operations on multiple rows, columns, and layers of data.For example, we can use 3D arrays to store the scores of students in multiple subjects.We can use the array to perform operations like finding the maximum score, minimum score, average score,etc.

## **Creating Array with Numpy**

In [9]:
a=np.array([1,2,3,4,5,6])
b=np.array([(7,8,9,10,11,12),(13,14,15,16,17,18)])

In [10]:
a
a.shape

(6,)

In [11]:
b
b.shape

(2, 6)

## **Initialize Arrays**

In [13]:
zeros=np.zeros((3,4))       # (rows, colomns)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
ones=np.ones((3,4))         # (rows, colomns)
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
full=np.full((3,4),5)       # (rows, colomns)
full

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [16]:
identity=np.identity(4)      # (rows, colomns)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## **Array Attirbutes**

In [19]:
a.shape      # number of rows or colomns in array

(6,)

In [20]:
len(a)      # number of elements in array

6

In [21]:
a.ndim      # number of dimensions  

1

In [22]:
a.size      # total number of elements in array

6

## **Basic Operation in Array**

In [24]:
k=a-b
k

array([[ -6,  -6,  -6,  -6,  -6,  -6],
       [-12, -12, -12, -12, -12, -12]])

In [25]:
k_1=np.add(a,b)
k_1

array([[ 8, 10, 12, 14, 16, 18],
       [14, 16, 18, 20, 22, 24]])

In [26]:
k_2=a/b
k_2

array([[0.14285714, 0.25      , 0.33333333, 0.4       , 0.45454545,
        0.5       ],
       [0.07692308, 0.14285714, 0.2       , 0.25      , 0.29411765,
        0.33333333]])

In [27]:
k_3=np.multiply(a,b)
k_3

array([[  7,  16,  27,  40,  55,  72],
       [ 13,  28,  45,  64,  85, 108]])

In [28]:
k_4=np.square(a)
k_4

array([ 1,  4,  9, 16, 25, 36])