# **Numpy_02**

In [1]:
# improt the necessay library of numpy
import numpy as np

In [2]:
# create an array that is empty with 5 rows and 3 columns
arr=np.empty((5,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
arr[4]

array([0., 0., 0.])

In [4]:
x=np.arange(10)     # create an array from 0 to 9 using arange function in numpy    
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# array of even numbers form 0 to 23 by the numpy   
even=np.arange(0,20,2)   # create an array from 0 to 19 in steps of 2
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
# array of odd numbers for 0 to 23 in the numpy
odd=np.arange(1,23,2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [7]:
# array on numbers with a specific difference
diff=np.arange(0,20,3)
diff

array([ 0,  3,  6,  9, 12, 15, 18])

In [8]:
# create an array uisng the linspace function in numpy
lin=np.linspace(0,10,5)
lin

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [9]:
# we can define the data type on the numpy array using the dtype function
dt=np.linspace(0,10,5,dtype='int64')
dt

array([ 0,  2,  5,  7, 10])

In [10]:
ones=np.ones((5,3),dtype='int64')
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

---
## **Assingnment**

### **What is the difference between int64 ,float32  64 and 16 ..... In ka maltalb kia hy?**

Acha, jab hum `int64`, `float32`, `float64`, aur `float16` ki baat karte hain, to ye **data types** hain jo numbers ko store karne ka tareeqa batate hain. Ye numbers store karne ki **size (bits)** aur **precision (accuracy)** define karte hain.

### **1. int64 (Integer 64-bit)**
- **Int** ka matlab hai **integer** (matlab poore numbers bina decimal ke, jaise 1, 2, -5, 100).
- `int64` ka matlab hai **64-bit integer**, jo bohot bare numbers store kar sakta hai.
- Iska range: \(-2^{63}\) se \(2^{63}-1\) tak hota hai.

#### **Example in Python**
```python
import numpy as np

x = np.int64(1000000000000)  # Ek bara number store karna
print(x, type(x))  # Output: 1000000000000 <class 'numpy.int64'>
```

---

### **2. float32 (Floating Point 32-bit)**
- **Float** ka matlab hai **decimal numbers** (jaise 3.14, -2.5, 0.0001).
- `float32` ek **32-bit floating point number** hai, jo decimals ko store karta hai.
- Chhoti memory use karta hai, lekin precision thodi kam hoti hai.

#### **Example in Python**
```python
y = np.float32(3.141592653589793)
print(y, type(y))  # Output: 3.1415927 <class 'numpy.float32'>
```
*Note:* `float32` sirf **7 decimal places** tak accuracy rakhta hai.

---

### **3. float64 (Floating Point 64-bit)**
- `float64` ek **64-bit floating point number** hai.
- Ye `float32` se zyada accurate hota hai aur **15-16 decimal places** tak store kar sakta hai.

#### **Example in Python**
```python
z = np.float64(3.141592653589793)
print(z, type(z))  # Output: 3.141592653589793 <class 'numpy.float64'>
```
*Note:* `float64` ki precision `float32` se zyada hoti hai.

---

### **4. float16 (Floating Point 16-bit)**
- `float16` ek **16-bit floating point number** hai.
- Chhoti memory use karta hai, lekin precision sirf **3-4 decimal places** tak hoti hai.
- Mostly **machine learning** aur **image processing** me use hota hai jahan memory save karni hoti hai.

#### **Example in Python**
```python
a = np.float16(3.141592653589793)
print(a, type(a))  # Output: 3.14 <class 'numpy.float16'>
```
*Note:* `float16` me sirf **3-4 decimal places** tak precision hoti hai.

---

### **Comparison Table**
| Data Type | Bits | Number Type | Precision |
|-----------|------|-------------|------------|
| int64     | 64   | Integer      | Poore numbers, bada range |
| float32   | 32   | Floating Point | ~7 decimal places |
| float64   | 64   | Floating Point | ~15-16 decimal places |
| float16   | 16   | Floating Point | ~3-4 decimal places |

---

In [ ]:
# sorting an array
sort=np.sort(ones)
sort

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## **Concatenate 1D Array**

In [12]:
a=np.array([1,2,3,4,5,6])
b=np.array([4,5,6,7,8,9])

In [13]:
contatanete=np.concatenate((a,b))
contatanete

array([1, 2, 3, 4, 5, 6, 4, 5, 6, 7, 8, 9])

In [14]:
sort=np.sort(contatanete)
sort

array([1, 2, 3, 4, 4, 5, 5, 6, 6, 7, 8, 9])

## **Concatenate 2D Array**

In [15]:
x=np.array([[1,2,3],[4,5,6]]) # create a 2D array
y=np.array([[7,8,9]])        # create a 1D array

In [16]:
# now we concenatate the 2D array and 1D array 
concatenate_1=np.concatenate((x,y),axis=0)      # for axis 1 the number of rows or the len of the array must be of same length.
concatenate_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
# create a 3D array
array=np.array([[[1,2,3],[4,5,6]],
                  [[4,5,6],[7,8,9]],
                  [[7,8,9],[10,11,12]]
                  ])
array.ndim

3

In [18]:
len(array)

3

In [19]:
array.size

18

In [20]:
array.dtype

dtype('int64')

In [21]:
array.shape

(3, 2, 3)

In [22]:
# now we reshape the array using the reshape function in numpy
reshape=np.reshape(array,(2,9))
reshape

array([[ 1,  2,  3,  4,  5,  6,  4,  5,  6],
       [ 7,  8,  9,  7,  8,  9, 10, 11, 12]])

In [23]:
reshape=np.reshape(array,(9,2))
reshape

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [24]:
reshape=np.reshape(array,(3,2,3))
reshape

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### **We can convert the 1d array to 2d and 3d array**

In [25]:
# now we create the 1d array 
n=np.array([1,2,3,4,5,6,7,8,9])
n

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# now we create the 2d array using this 1d array that is n 
n_2d=np.reshape(n,(3,3))
n_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
# now we convert the 1d array into 3d array 
n_3d=np.reshape(n,(3,1,3))
n_3d

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [28]:
n_1=n[np.newaxis, :].shape
n_1

(1, 9)

In [29]:
n_2=n[:, np.newaxis].shape
n_2

(9, 1)

### **Now do the Indexing and Slicing in the Numpy Library**

In [30]:
# now we do the indexing and slicing in the numpy array 
array=np.array([1,2,3,4,5,6,7,8,9])
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# now i do the indexing in the numpy array
array[2:5]

array([3, 4, 5])

In [32]:
# now do the slicing on the numpy array 
array[1:3]

array([2, 3])