# **Liner Algebra in Python**

In [1]:
# import the numpy library
import numpy as np

In [2]:
# create a cofficient of matrix A.
A=np.array([[1,2,3],[4,5,6],[7,8,9]])           # 3x3 matrix
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
#  Constant Matrix B.
B=np.array([11,22,33])          # 3x1 Matrix B
print(B)

[11 22 33]


In [4]:
# Now solve this for X.
X=np.linalg.solve(A,B)          # X is a 3x1 matrix
print(X)

[-19.66666667  39.33333333 -16.        ]
