# **SVD in Python**

In [1]:
# import the necessary libraries
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# generate a matrix  of 4x3 dataset
A = np.random.rand(4,3)
A

array([[0.89291106, 0.31002303, 0.24034105],
       [0.02851656, 0.09530449, 0.24173395],
       [0.99011076, 0.27508145, 0.82533007],
       [0.68549366, 0.1391146 , 0.45713034]])

In [3]:
# lets apply SVD here
U, Sigma, VT = np.linalg.svd(A)
# print each matrix separately
print("U Matrix=", U)
print("--------------------------------")
print("Sigma Matrix=",Sigma)
print("--------------------------------")
print("VT Matrix=",VT)

U Matrix= [[-0.5121491   0.76547048  0.38925936  0.01534289]
 [-0.09487594 -0.46517566  0.77337027  0.42012925]
 [-0.71986479 -0.43917737 -0.06245111 -0.53387056]
 [-0.45879901 -0.06920833 -0.49646293  0.73364721]]
--------------------------------
Sigma Matrix= [1.81626785 0.37854419 0.11294474]
--------------------------------
VT Matrix= [[-0.81885434 -0.236566   -0.52298575]
 [ 0.49652257  0.16521905 -0.85215492]
 [-0.28799809  0.95746498  0.01782998]]


In [4]:
U.shape

(4, 4)

In [5]:
Sigma.shape

(3,)

In [6]:
VT.shape

(3, 3)