# **Numpy Indexing and Slicing**

In [1]:
# import the necessary library
import numpy as np

In [2]:
# create an array 
a=np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
a[0]        # indexing to see the first observation in the array

np.int64(1)

In [4]:
a[-1]       # indexing to see the last observation in the array

np.int64(10)

In [5]:
# now i create another array uisng arange function in the numpy library
b=np.arange(1,20,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [6]:
b[2]

np.int64(5)

In [7]:
# now i reshape the array in the numpy library
c=b.reshape(2,5)
c

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [8]:
# now we see the indexing of the c array 
c[0]

array([1, 3, 5, 7, 9])

In [9]:
c[1]

array([11, 13, 15, 17, 19])