# **Matrix  or Matrices**

In [41]:
# import the necessay library
import numpy as np

In [42]:
# now we create the 2 x 3 matrix 
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [43]:
# create a matrix of big dimension
b=np.arange(0,100,2)
print(b)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [44]:
print(a[1])

[4 5 6]


In [45]:
print(b[1])

2


In [46]:
b_shape=b.reshape(5,10)
print(b_shape)

[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]


In [47]:
# slicing the matrix
b_shape[1:3,2:4]

array([[24, 26],
       [44, 46]])

## **Now we see the min , max and the sum of the values in the matrices**

In [48]:
b_shape.min()

np.int64(0)

In [49]:
b_shape.max()

np.int64(98)

In [50]:
b_shape.sum()

np.int64(2450)

In [51]:
b_shape.min(axis=0)     # min of each column

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [52]:
b_shape.min(axis=1)     # min of each row

array([ 0, 20, 40, 60, 80])

In [53]:
b_shape.max(axis=0)     # max of each column

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [54]:
b_shape.max(axis=1)     # max of each row

array([18, 38, 58, 78, 98])

### **Add numbers in Rows or Colomns in the Martix**

In [55]:
# now we create a new array using the arange function
c=np.arange(10,50,2).reshape(5,4)
print(c)

[[10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]
 [42 44 46 48]]


In [56]:
c+np.array([50,52,54,56])

array([[ 60,  64,  68,  72],
       [ 68,  72,  76,  80],
       [ 76,  80,  84,  88],
       [ 84,  88,  92,  96],
       [ 92,  96, 100, 104]])

In [57]:
# Add a new row
c=np.append(c,[[10,12,14,16]],axis=0)
print(c)

[[10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]
 [42 44 46 48]
 [10 12 14 16]]


In [60]:
# Add a new column to matrix c
c = np.append(c, [[18], [20], [22], [24], [26], [28]], axis=1)
print(c)

[[10 12 14 16 18]
 [18 20 22 24 20]
 [26 28 30 32 22]
 [34 36 38 40 24]
 [42 44 46 48 26]
 [10 12 14 16 28]]


In [37]:
# Reverse an array
c[::-1]

array([[42, 44, 46, 48],
       [34, 36, 38, 40],
       [26, 28, 30, 32],
       [18, 20, 22, 24],
       [10, 12, 14, 16]])