# **Create an Array for Existing Dataset**

In [1]:
# import the necessary library
import numpy as np

In [2]:
a=np.arange(0,250,5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220, 225, 230, 235, 240, 245])

In [3]:
len(a)

50

In [4]:
# now we create an arry from the a list
a[25:45]

array([125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185,
       190, 195, 200, 205, 210, 215, 220])

In [5]:
# now stack the two arrays horizontally 
a_1=np.array([1,2,3,4,5,6,7,8,9,10])
b_1=np.array([11,12,13,14,15,16,17,18,19,20])

In [6]:
stack=np.vstack((a_1,b_1))
stack

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [7]:
d=stack.reshape(2,5,2)
d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])